// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/signalg/v1/connected.proto

package signalgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectedConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PingIntervalMs int64                  `protobuf:"varint,1,opt,name=ping_interval_ms,json=pingIntervalMs,proto3" json:"ping_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectedConfig) Reset() {
	*x = ConnectedConfig{}
	mi := &file_proto_signalg_v1_connected_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedConfig) ProtoMessage() {}

func (x *ConnectedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signalg_v1_connected_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedConfig.ProtoReflect.Descriptor instead.
func (*ConnectedConfig) Descriptor() ([]byte, []int) {
	return file_proto_signalg_v1_connected_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectedConfig) GetPingIntervalMs() int64 {
	if x != nil {
		return x.PingIntervalMs
	}
	return 0
}

type ConnectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Config        *ConnectedConfig       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedPayload) Reset() {
	*x = ConnectedPayload{}
	mi := &file_proto_signalg_v1_connected_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedPayload) ProtoMessage() {}

func (x *ConnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signalg_v1_connected_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedPayload.ProtoReflect.Descriptor instead.
func (*ConnectedPayload) Descriptor() ([]byte, []int) {
	return file_proto_signalg_v1_connected_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectedPayload) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectedPayload) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ConnectedPayload) GetConfig() *ConnectedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_proto_signalg_v1_connected_proto protoreflect.FileDescriptor

const file_proto_signalg_v1_connected_proto_rawDesc = "" +
	"\n" +
	" proto/signalg/v1/connected.proto\x12\n" +
	"signalg.v1\";\n" +
	"\x0fConnectedConfig\x12(\n" +
	"\x10ping_interval_ms\x18\x01 \x01(\x03R\x0epingIntervalMs\"\xa6\x01\n" +
	"\x10ConnectedPayload\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.signalg.v1.ConnectedConfigR\x06configB;Z9github.com/project-kgo/signalg/proto/signalg/v1;signalgv1b\x06proto3"

var (
	file_proto_signalg_v1_connected_proto_rawDescOnce sync.Once
	file_proto_signalg_v1_connected_proto_rawDescData []byte
)

func file_proto_signalg_v1_connected_proto_rawDescGZIP() []byte {
	file_proto_signalg_v1_connected_proto_rawDescOnce.Do(func() {
		file_proto_signalg_v1_connected_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signalg_v1_connected_proto_rawDesc), len(file_proto_signalg_v1_connected_proto_rawDesc)))
	})
	return file_proto_signalg_v1_connected_proto_rawDescData
}

var file_proto_signalg_v1_connected_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_signalg_v1_connected_proto_goTypes = []any{
	(*ConnectedConfig)(nil),  // 0: signalg.v1.ConnectedConfig
	(*ConnectedPayload)(nil), // 1: signalg.v1.ConnectedPayload
}
var file_proto_signalg_v1_connected_proto_depIdxs = []int32{
	0, // 0: signalg.v1.ConnectedPayload.config:type_name -> signalg.v1.ConnectedConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_signalg_v1_connected_proto_init() }
func file_proto_signalg_v1_connected_proto_init() {
	if File_proto_signalg_v1_connected_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signalg_v1_connected_proto_rawDesc), len(file_proto_signalg_v1_connected_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_signalg_v1_connected_proto_goTypes,
		DependencyIndexes: file_proto_signalg_v1_connected_proto_depIdxs,
		MessageInfos:      file_proto_signalg_v1_connected_proto_msgTypes,
	}.Build()
	File_proto_signalg_v1_connected_proto = out.File
	file_proto_signalg_v1_connected_proto_goTypes = nil
	file_proto_signalg_v1_connected_proto_depIdxs = nil
}
